AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for advanced request routing with EC2 and ALB

Parameters:
  KeyPairName:
    Type: String
    Description: EC2 Key Pair Name
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
  DefaultVpcId:
    Type: AWS::EC2::VPC::Id
  SubnetIdA:
    Type: AWS::EC2::Subnet::Id
  SubnetIdB:
    Type: AWS::EC2::Subnet::Id
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: Hosted Zone ID for your domain
  DNSRecordName:
    Type: String
    Default: myteambridge.com
    Description: DNS name to point to the ALB

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: advanced-routing-sec-grp
      GroupDescription: Allow HTTP and SSH
      VpcId: !Ref DefaultVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: advanced-routing-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: advanced-routing-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: arn:aws:s3:::advanced-request-routing-bucket-123/*

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref IAMRole

  DevInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyPairName
      SubnetId: !Ref SubnetIdA
      SecurityGroupIds:
        - !Ref SecurityGroup
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: dev
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          mkdir /var/www/html/dev
          cd /var/www/html/dev
          aws s3 cp s3://advanced-request-routing-bucket-123/hw-dev.css ./
          aws s3 cp s3://advanced-request-routing-bucket-123/hw-dev-py.css ./
          aws s3 cp s3://advanced-request-routing-bucket-123/python.png ./
          aws s3 cp s3://advanced-request-routing-bucket-123/apache.svg ./
          aws s3 cp s3://advanced-request-routing-bucket-123/dev-index.html ./index.html
          cd /var/www/html
          aws s3 cp s3://advanced-request-routing-bucket-123/hw-dev.css ./
          aws s3 cp s3://advanced-request-routing-bucket-123/hw-dev-py.css ./
          aws s3 cp s3://advanced-request-routing-bucket-123/python.png ./
          aws s3 cp s3://advanced-request-routing-bucket-123/apache.svg ./
          aws s3 cp s3://advanced-request-routing-bucket-123/dev-root-index.html ./index.html
          systemctl restart httpd

  StgInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyPairName
      SubnetId: !Ref SubnetIdB
      SecurityGroupIds:
        - !Ref SecurityGroup
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: stg
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          mkdir /var/www/html/stg
          cd /var/www/html/stg
          aws s3 cp s3://advanced-request-routing-bucket-123/hw-stg.css ./
          aws s3 cp s3://advanced-request-routing-bucket-123/hw-stg-py.css ./
          aws s3 cp s3://advanced-request-routing-bucket-123/python.png ./
          aws s3 cp s3://advanced-request-routing-bucket-123/apache.svg ./
          aws s3 cp s3://advanced-request-routing-bucket-123/stg-index.html ./index.html
          cd /var/www/html
          aws s3 cp s3://advanced-request-routing-bucket-123/hw-stg.css ./
          aws s3 cp s3://advanced-request-routing-bucket-123/hw-stg-py.css ./
          aws s3 cp s3://advanced-request-routing-bucket-123/python.png ./
          aws s3 cp s3://advanced-request-routing-bucket-123/apache.svg ./
          aws s3 cp s3://advanced-request-routing-bucket-123/stg-root-index.html ./index.html
          systemctl restart httpd

  DevTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: dev-target-group
      Protocol: HTTP
      Port: 80
      VpcId: !Ref DefaultVpcId
      HealthCheckPath: /dev/index.html
      TargetType: instance
      Targets:
        - Id: !Ref DevInstance

  StgTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: stg-target-group
      Protocol: HTTP
      Port: 80
      VpcId: !Ref DefaultVpcId
      HealthCheckPath: /stg/index.html
      TargetType: instance
      Targets:
        - Id: !Ref StgInstance

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: advanced-routing-alb
      Subnets:
        - !Ref SubnetIdA
        - !Ref SubnetIdB
      SecurityGroups:
        - !Ref SecurityGroup
      Scheme: internet-facing
      Type: application

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DevTargetGroup

  ListenerRuleDev:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref Listener
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values:
            - /dev*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref DevTargetGroup

  ListenerRuleStg:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref Listener
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - /stg*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref StgTargetGroup

  ALBDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DNSRecordName
      Type: A
      AliasTarget:
        DNSName: !GetAtt LoadBalancer.DNSName
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
